### ISSUE TITLE
access to _requests is not synchronized and may lead to SIGABORT

### ISSUE THREAD

**Issue by Sega-Zero** [path/FastImageCache#94]
I've just caught an SIGABORT with this error message:
> *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFType _cfurl]: unrecognized selector sent to instance 0x1700ad200'

which is occured on the main queue in ```_retrieveImageForEntity:withFormatName:loadSynchronously:completionBlock:``` at line 205:
```objectivec
// We check to see if this image is already being fetched.
NSMutableDictionary *requestDictionary = [_requests objectForKey:sourceImageURL];
```

When looking at the callstack and queues, I've noticed another queue with the same method call.
I guess ```_imageDidLoad:forURL:``` may have modified _requests dictionary, so the one in the main queue was failed to read from it.

Isn't ```asynchronouslyRetrieveImageForEntity:withFormatName:completionBlock:``` thread-safe?

**Comment by epatey** [comment]
My reading of the code and documentation suggest that it's up to the user of FIC to help ensure thread safety. The documentation does suggest the following:

> Note: The completion block must be called on the main thread. Fast Image Cache is architected such that this call will not block the main thread, as processing sources image is handled in the image cache's own serial dispatch queue.

That completion block is `_imageDidLoad:forURL:`. If you also only call `retrieveImageForEntity:` and `cancelImageRetrievalForEntity:` from the main thread, you'll be all set.

Otherwise, you're right, `_resources` could be access concurrently from multiple threads.

**Comment by mallorypaine** [comment]
Thanks @epatey for the explanation. Indeed you're right and the documentation does need to be followed. If you call things from unexpected threads, you'll get unexpected (i.e. undesirable) results :-)
